version: "3"

services:
  backend:
    build:
      context: ./backend
    container_name: biblio_python
    ports:
    - "8000:8000"
    volumes:
    - ./backend:/app
    environement:
    - DATABASE_URL=postgresql://postgres:password@db:5432/biblio
    depends_on:
    - db

  db:
    image: postgres:15
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: biblio

volumes:
  postgres-data: